import { env } from 'cloudflare:workers';
import { seedProjects, type TrackerProject, type TrackerTask } from '@/lib/tracker-data';
const now=()=>new Date().toISOString(); const db=()=>{if(!env.DB)throw new Error('Database unavailable');return env.DB};
export async function listProjects():Promise<TrackerProject[]>{const database=db();const count=await database.prepare('SELECT COUNT(*) AS n FROM projects').first<{n:number}>();if(!count?.n){const stamp=now();const statements=[];for(const p of seedProjects){statements.push(database.prepare('INSERT INTO projects (id,name,description,priority,start_date,target_end_date,notes,archived,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.name,p.description,p.priority,p.startDate,p.targetEndDate,p.notes,p.archived?1:0,stamp,stamp));for(const t of p.tasks)statements.push(database.prepare('INSERT INTO tasks (id,project_id,name,type,owner,start_date,due_date,percent_complete,priority,manual_status_override,notes,sort_order,archived,predecessor,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(t.id,t.projectId,t.name,t.type,t.owner,t.startDate,t.dueDate,t.percentComplete,t.priority,t.manualStatusOverride,t.notes,t.sortOrder,t.archived?1:0,t.predecessor||null,stamp,stamp))}await database.batch(statements)}const ps=await database.prepare('SELECT * FROM projects ORDER BY archived, target_end_date').all<Record<string,unknown>>();const ts=await database.prepare('SELECT * FROM tasks ORDER BY project_id, sort_order').all<Record<string,unknown>>();return ps.results.map(row=>({...mapProject(row),tasks:ts.results.filter(t=>Number(t.project_id)===Number(row.id)).map(mapTask)}))}
const mapProject=(r:Record<string,unknown>)=>({id:Number(r.id),name:String(r.name),description:String(r.description),priority:String(r.priority) as TrackerProject['priority'],startDate:String(r.start_date),targetEndDate:String(r.target_end_date),notes:String(r.notes),archived:Boolean(r.archived)}) as Omit<TrackerProject,'tasks'>;
const mapTask=(r:Record<string,unknown>)=>({id:Number(r.id),projectId:Number(r.project_id),name:String(r.name),type:String(r.type),owner:String(r.owner),startDate:r.start_date?String(r.start_date):null,dueDate:r.due_date?String(r.due_date):null,percentComplete:Number(r.percent_complete),priority:String(r.priority),manualStatusOverride:r.manual_status_override?String(r.manual_status_override):null,notes:String(r.notes),sortOrder:Number(r.sort_order),archived:Boolean(r.archived),predecessor:r.predecessor?Number(r.predecessor):null}) as TrackerTask;
export async function saveProject(p:TrackerProject){const s=now();await db().prepare('INSERT INTO projects (id,name,description,priority,start_date,target_end_date,notes,archived,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,priority=excluded.priority,start_date=excluded.start_date,target_end_date=excluded.target_end_date,notes=excluded.notes,archived=excluded.archived,updated_at=excluded.updated_at').bind(p.id,p.name,p.description,p.priority,p.startDate,p.targetEndDate,p.notes,p.archived?1:0,s,s).run()}
export async function saveTask(t:TrackerTask){const s=now();await db().prepare('INSERT INTO tasks (id,project_id,name,type,owner,start_date,due_date,percent_complete,priority,manual_status_override,notes,sort_order,archived,predecessor,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id,name=excluded.name,type=excluded.type,owner=excluded.owner,start_date=excluded.start_date,due_date=excluded.due_date,percent_complete=excluded.percent_complete,priority=excluded.priority,manual_status_override=excluded.manual_status_override,notes=excluded.notes,sort_order=excluded.sort_order,archived=excluded.archived,predecessor=excluded.predecessor,updated_at=excluded.updated_at').bind(t.id,t.projectId,t.name,t.type,t.owner,t.startDate,t.dueDate,t.percentComplete,t.priority,t.manualStatusOverride,t.notes,t.sortOrder,t.archived?1:0,t.predecessor||null,s,s).run()}
export async function setArchive(table:'projects'|'tasks',id:number,value:boolean){await db().prepare(`UPDATE ${table} SET archived=?, updated_at=? WHERE id=?`).bind(value?1:0,now(),id).run()}
